apiVersion: template.openshift.io/v1
kind: Template
metadata:
  name: demo-openshift-express

parameters:
- name: APP_NAME
  description: The name of the application
  required: true
  value: demo-express
- name: SOURCE_REPOSITORY_URL
  description: Source Repository
  required: true
  value: https://github.com/gary-jipp/demo-openshift-express
- name: SOURCE_REPOSITORY_REF
  description: Source Repository
  required: true
  value: master
- name: CONTEXT_DIR
  description: Source Directory if not master
  required: true
  value: app

objects:

- apiVersion: image.openshift.io/v1
  kind: ImageStream
  metadata:
    name: ${APP_NAME}
  spec:
    lookupPolicy:
      local: true

- kind: PersistentVolumeClaim
  apiVersion: v1
  metadata:
    name: ${APP_NAME}-storage
  spec:
    accessModes:
      - ReadWriteOnce
    resources:
      requests:
        storage: 50Mi

- kind: BuildConfig
  apiVersion: build.openshift.io/v1
  metadata:
    labels:
      app: ${APP_NAME}
    name: ${APP_NAME}
  spec:
    source:
      contextDir: ${CONTEXT_DIR}
      git:
        ref: ${SOURCE_REPOSITORY_REF}
        uri: ${SOURCE_REPOSITORY_URL}
    strategy:
      dockerStrategy:
        from:
          kind: ImageStreamTag
          name: node:16-alpine
    output:
      to:
        kind: ImageStreamTag
        name: ${APP_NAME}:latest

- kind: Deployment
  apiVersion: apps/v1
  metadata:
    annotations:
      image.openshift.io/triggers: '[{"from":{"kind":"ImageStreamTag","name":"${APP_NAME}:latest"},"fieldPath":"spec.template.spec.containers[?(@.name==\"${APP_NAME}\")].image"}]'
    name: ${APP_NAME}
    # namespace: crt-redhat2304-dev
  spec:
    replicas: 2
    selector:
      matchLabels:
        deployment: ${APP_NAME}
    template:
      metadata:
        labels:
          deployment: ${APP_NAME}
      spec:
        containers:
          - name: ${APP_NAME}
            image: ${APP_NAME}:latest
            ports:
              - containerPort: 8080
                protocol: TCP
        restartPolicy: Always

- kind: Service
  apiVersion: v1
  metadata:
    name: ${APP_NAME}
    labels:
      app: ${APP_NAME}
  spec:
    ipFamilies:
      - IPv4
    ports:
      - name: 8080-tcp
        protocol: TCP
        port: 8080
        targetPort: 8080
    type: ClusterIP
    selector:
      deployment: ${APP_NAME}

- kind: Route
  apiVersion: route.openshift.io/v1
  metadata:
    name: ${APP_NAME}
    labels: {}
  spec:
    to:
      kind: Service
      name: ${APP_NAME}
    tls: null
    port:
      targetPort: 8080